language: python

python:
  - 3.8
  - 3.7
  - 3.6

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

env:
  - PG_VERSION=latest
  - PG_VERSION=12.2
  - PG_VERSION=11.7
  - PG_VERSION=10.12
  - PG_VERSION=9.6
  - SQLA_VERSION=1
  - SQLA_VERSION=1.3.2

install:
  - pip install pip -U
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - pip install codecov
  - poetry add "sqlalchemy==$SQLA_VERSION"
  - poetry install -v

before_script: docker-compose up -d && sleep 3
script: poetry run pytest --cov=sqlalchemy_facets tests/

after_success:
  - codecov

jobs:
  fast_finish: true
  include:
    - stage: publish
      script: skip
      deploy:
        - provider: script
          script: poetry publish --build -u $PYPI_USER -p $PYPI_PASSWD
          on:
            branch: master
            tags: true
