language: python

stages:
  - test

cache:
  pip: true
  directories:
    - $HOME/.cache/pypoetry

jobs:
  fast_finish: true
  include:
    - python: 3.8

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - pip install pip -U
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env
  - poetry install -v
  - poetry build -v
  - docker-compose up -d

script: poetry run pytest --cov=sqlalchemy_facets tests/